
name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build
      uses: cjerrington/actions-eleventy@master
      with:
        install_dependencies: true

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: _site
        publish_branch: pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
